@extends('layouts.app') @section('content')
<div class="max-w-4xl mx-auto">
    <div class="mb-8">
        <h1 class="text-3xl font-extrabold text-slate-900 tracking-tight">Security & MFA</h1>
        <p class="text-slate-500 font-medium mt-1">Protect your HR account with strong passwords and two-factor authentication.</p>
    </div>

    <div class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden mb-8">
        <div class="p-6 border-b border-slate-100 bg-slate-50">
            <h3 class="text-sm font-bold text-slate-800">Change Password</h3>
        </div>
        <form class="p-6 space-y-6">
            <div>
                <label class="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Current Password</label>
                <input type="password" placeholder="••••••••" class="w-full md:w-1/2 border-slate-200 rounded-lg text-sm font-bold text-slate-700 p-3">
            </div>
            <div>
                <label class="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">New Password</label>
                <input type="password" placeholder="••••••••" class="w-full md:w-1/2 border-slate-200 rounded-lg text-sm font-bold text-slate-700 p-3">
            </div>
            <div>
                <label class="block text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Confirm New Password</label>
                <input type="password" placeholder="••••••••" class="w-full md:w-1/2 border-slate-200 rounded-lg text-sm font-bold text-slate-700 p-3">
            </div>
            <div class="pt-2">
                <button type="button" class="bg-[#0B1C3D] hover:bg-slate-800 text-white px-6 py-2.5 rounded-lg font-bold text-sm transition shadow-sm">
                    Update Password
                </button>
            </div>
        </form>
    </div>

    <div class="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div class="p-6 border-b border-slate-100 bg-slate-50 flex items-center justify-between">
            <h3 class="text-sm font-bold text-slate-800">Two-Factor Authentication (MFA)</h3>
            <span class="px-3 py-1 bg-amber-100 text-amber-700 text-xs font-bold rounded-full">Inactive</span>
        </div>
        <div class="p-6">
            <p class="text-sm text-slate-600 mb-6">Add an extra layer of security to your account. Once enabled, you'll be required to enter a code generated by an authenticator app on your phone during login.</p>
            <button type="button" class="bg-[#22C55E] hover:bg-emerald-600 text-white px-6 py-2.5 rounded-lg font-bold text-sm transition shadow-sm">
                Enable MFA
            </button>
        </div>
    </div>
</div>
@endsection